USE EmpresaDeReciclagem;

-- 1️⃣ DOCUMENTO_VENDA → índice por CLIENTE
CREATE INDEX idx_DOCUMENTO_VENDA_CLIENTE
ON DOCUMENTO_VENDA (id_CLIENTE);

-- Teste do índice
SELECT * 
FROM DOCUMENTO_VENDA 
WHERE id_CLIENTE = (SELECT id_CLIENTE FROM CLIENTE LIMIT 1);

-- 2️⃣ DOCUMENTO_COLETA → índice por data
CREATE INDEX idx_DOCUMENTO_COLETA_data
ON DOCUMENTO_COLETA (data);

-- Teste do índice
SELECT * 
FROM DOCUMENTO_COLETA 
WHERE data = '2025-09-21';

-- 3️⃣ MATERIAL → índice por tipo
CREATE INDEX idx_MATERIAL_tipo
ON MATERIAL (tipo);

-- Teste do índice
SELECT * 
FROM MATERIAL 
WHERE tipo = 'Plástico';

-- 4️⃣ CLIENTE → índice por cpf_cnpj
CREATE INDEX idx_CLIENTE_cpf_cnpj
ON CLIENTE (cpf_cnpj);

-- Teste do índice
SELECT * 
FROM CLIENTE 
WHERE cpf_cnpj = '111.222.333/0001-44';

-- 5️⃣ FUNCIONARIO_SEPARA_MATERIAL → índice por id_FUNCIONARIO
CREATE INDEX idx_FUNCIONARIO_separa_FUNCIONARIO
ON FUNCIONARIO_SEPARA_MATERIAL (id_FUNCIONARIO);

-- Teste do índice
SELECT * 
FROM FUNCIONARIO_SEPARA_MATERIAL 
WHERE id_FUNCIONARIO = (SELECT id_FUNCIONARIO FROM FUNCIONARIO LIMIT 1);
